#include <iostream>
#include <cmath>

void OE_compute_u(double** u, double xi, double eta, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m_0, double** m_1, double** m_2, double** m_3, double** m_4, double** m_5);
void OE_compute_u_ave(double** u_ave, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m_0, double** m_1, double** m_2, double** m_3, double** m_4, double** m_5);
void OE_compute_e_alpha(double** e_alpha, double xi, double eta, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m1_0, double** m1_1, double** m1_2, double** m1_3, double** m1_4, double** m1_5, double** m2_0, double** m2_1, double** m2_2, double** m2_3, double** m2_4, double** m2_5, double** Ealpha_0, double** Ealpha_1, double** Ealpha_2, double** Ealpha_3, double** Ealpha_4, double** Ealpha_5);
void OE_compute_e_alpha_ave(double** u_ave, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m1_0, double** m1_1, double** m1_2, double** m1_3, double** m1_4, double** m1_5, double** m2_0, double** m2_1, double** m2_2, double** m2_3, double** m2_4, double** m2_5, double** Ealpha_0, double** Ealpha_1, double** Ealpha_2, double** Ealpha_3, double** Ealpha_4, double** Ealpha_5);
void OE_compute_Cs_ave(double** Cs_ave, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m1_0, double** m1_1, double** m1_2, double** m1_3, double** m1_4, double** m1_5, double** m2_0, double** m2_1, double** m2_2, double** m2_3, double** m2_4, double** m2_5, double** Ee_0, double** Ee_1, double** Ee_2, double** Ee_3, double** Ee_4, double** Ee_5, double** Ei_0, double** Ei_1, double** Ei_2, double** Ei_3, double** Ei_4, double** Ei_5, double** Er_0, double** Er_1, double** Er_2, double** Er_3, double** Er_4, double** Er_5);
void OE_compute_beta_ij(double** beta_ij_x, double** beta_ij_y, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m1_0, double** m1_1, double** m1_2, double** m1_3, double** m1_4, double** m1_5, double** m2_0, double** m2_1, double** m2_2, double** m2_3, double** m2_4, double** m2_5, double** Ee_0, double** Ee_1, double** Ee_2, double** Ee_3, double** Ee_4, double** Ee_5, double** Ei_0, double** Ei_1, double** Ei_2, double** Ei_3, double** Ei_4, double** Ei_5, double** Er_0, double** Er_1, double** Er_2, double** Er_3, double** Er_4, double** Er_5);
void OE_compute_scalar_sigma(double* Linf, double** sigma_0_x, double** sigma_1_x, double** sigma_2_x, double** sigma_0_y, double** sigma_1_y, double** sigma_2_y, double** u_0, double** u_1, double** u_2, double** u_3, double** u_4, double** u_5, double h_x, double h_y);
void OE_compute_system_sigma(double** sigma_0, double** sigma_1, double** sigma_2, double** rho_0, double** rho_1, double** rho_2, double** rho_3, double** rho_4, double** rho_5, double** m1_0, double** m1_1, double** m1_2, double** m1_3, double** m1_4, double** m1_5, double** m2_0, double** m2_1, double** m2_2, double** m2_3, double** m2_4, double** m2_5, double** Ee_0, double** Ee_1, double** Ee_2, double** Ee_3, double** Ee_4, double** Ee_5, double** Ei_0, double** Ei_1, double** Ei_2, double** Ei_3, double** Ei_4, double** Ei_5, double** Er_0, double** Er_1, double** Er_2, double** Er_3, double** Er_4, double** Er_5, double h_x, double h_y);
void OE_procedure(double** u_1, double** u_2, double** u_3, double** u_4, double** u_5, double** sigma_0, double** sigma_1, double** sigma_2, double tau);

